version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    volumes:
      - ./app:/app
    ports:
      - 8000:80
    environment:
      - DATABASE_URL=postgresql://postgres:password12345@db:5432/fastapi
    depends_on:
      - db
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5432:5432
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_SERVER=db
      - POSTGRES_PASSWORD=password12345
      - POSTGRES_DB=fastapi

volumes:
  postgres_data:
